apiVersion: v1
kind: Service
metadata:
  name: ai-app-service
  namespace: default
spec:
  type: LoadBalancer  # This creates a load balancer
  ports:
    - port: 80  # External port
      targetPort: 5000  # Port your Flask app is running on
  selector:
    app: ai-app  # Make sure this matches the labels of your pod

